### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Carlopasquinucci** [AllwineDesigns/stl_cmd#7]
Do you have in mind to implement the features that are present in the readme file?
Thanks

**Comment by jallwine** [comment]
Which ones do you have in mind? I don't actively develop this tool, but a few have been implemented that aren't documented in the readme.

**Comment by Carlopasquinucci** [comment]
Hey Jallwine, thansk for the answer!
I would like to calculate the volume of the stl file, because I need for 3D printing.
It is not necessarly that is 100% accurate, it is only to estimate it.

This is the most interesting and most complex command I think.

Thanks a lot,
Carlo

**Comment by jallwine** [comment]
Calculating the volume is actually fairly straight forward. See this blog post for the details of how to do it: https://n-e-r-v-o-u-s.com/blog/?p=4415

I went ahead and added an stl_volume that performs the calculation: https://github.com/AllwineDesigns/stl_cmd/blob/master/src/stl_volume.cpp

**Comment by Carlopasquinucci** [comment]
Thanks a lot!
