### ISSUE TITLE
New release on Debian?

### ISSUE THREAD

**Issue by fi0** [AllwineDesigns/stl_cmd#8]
Will there be a new tagged release? or is there a easy way to install a newer version? Thank you!

**Comment by jallwine** [comment]
I’d like to eventually, but I’m not sure when I’ll have the time to figure out that process again. In the meantime, it should be easy to compile the latest as it has no dependencies. You can follow the instructions here: https://github.com/AllwineDesigns/stl_cmd

**Comment by jallwine** [comment]
Also, you don’t have to do make install. Running make will create a local bin directory and you can change your path to include that directory. That way you won’t pollute your system files that were installed with the package.

**Comment by fi0** [comment]
Thank you!
