### ISSUE TITLE
Overflow issue on large ~5GB files

### ISSUE THREAD

**Issue by bartoszek** [AllwineDesigns/stl_cmd#9]
`num_tris` has to be casted to `uint64_t` here to prevent overflowing when calculating size for stl with ~100M triangles.
https://github.com/AllwineDesigns/stl_cmd/blob/5d1c0a24387e174e41d4c964703b455e974286c9/src/stl_util.h#L303

**Comment by jallwine** [comment]
Good catch! Did you run into this problem or were you just looking through the code?

**Comment by bartoszek** [comment]
I was doing some synthetic tests for 3d printer manufacturer and stl_marge strangely stopped working for me.
